const fs = require('fs');

function generateLayouts() {
    let sql = `
-- Migration: Add 140+ Professional Layouts
-- Generated by Antigravity

-- Optional: You may want to truncate or leave existing ones. 
-- TRUNCATE TABLE album_layouts; 

INSERT INTO album_layouts (name, category, image_count, aspect_ratio, is_spread, config, is_active) VALUES 
`;

    const values = [];

    // --- Helper Config Generators ---

    // 1. Grid Generator
    const generateGrid = (count, isSpread) => {
        const w = isSpread ? 200 : 100;
        const h = 100;
        const slots = [];

        let cols = Math.ceil(Math.sqrt(count));
        let rows = Math.ceil(count / cols);

        // Adjust for spread
        if (isSpread) cols = Math.ceil(count / 2);

        const cellW = w / cols;
        const cellH = h / rows;

        let added = 0;
        for (let r = 0; r < rows; r++) {
            for (let c = 0; c < cols; c++) {
                if (added >= count) break;

                slots.push({
                    left: Number((c * cellW).toFixed(2)),
                    top: Number((r * cellH).toFixed(2)),
                    width: Number(cellW.toFixed(2)),
                    height: Number(cellH.toFixed(2)),
                    rotation: 0,
                    z_index: added
                });
                added++;
            }
        }
        return slots;
    };

    // 2. BSP (Binary Space Partitioning)
    const generateBSP = (count, isSpread) => {
        const w = isSpread ? 200 : 100;
        const h = 100;

        let rects = [{ x: 0, y: 0, w: w, h: h }];

        // Iteratively split random rect until we have 'count' rects
        while (rects.length < count) {
            // Pick a random rect to split (prefer larger ones)
            rects.sort((a, b) => (b.w * b.h) - (a.w * a.h));
            const targetIndex = 0;
            const target = rects[targetIndex];
            rects.splice(targetIndex, 1);

            // Split Horz or Vert?
            const splitVert = target.w > target.h * (isSpread ? 1.5 : 1);

            const splitPct = 0.3 + (Math.random() * 0.4); // 30-70% split

            if (splitVert) {
                const w1 = target.w * splitPct;
                const w2 = target.w - w1;
                rects.push({ x: target.x, y: target.y, w: w1, h: target.h });
                rects.push({ x: target.x + w1, y: target.y, w: w2, h: target.h });
            } else {
                const h1 = target.h * splitPct;
                const h2 = target.h - h1;
                rects.push({ x: target.x, y: target.y, w: target.w, h: h1 });
                rects.push({ x: target.x, y: target.y + h1, w: target.w, h: h2 });
            }
        }

        // Gap / Padding Logic
        const applyGap = Math.random() > 0.3; // 70% have gaps
        const margin = applyGap ? (0.5 + Math.random() * 2) : 0;

        return rects.map((r, i) => ({
            left: Number((r.x + margin).toFixed(2)),
            top: Number((r.y + margin).toFixed(2)),
            width: Number((r.w - margin * 2).toFixed(2)),
            height: Number((r.h - margin * 2).toFixed(2)),
            rotation: 0,
            z_index: i
        }));
    };


    // --- Single Page Layouts (1-6) ---
    const counts = [1, 2, 3, 4, 5, 6];

    counts.forEach(cnt => {
        for (let i = 0; i < 20; i++) {
            const isSymmetric = i < 5;

            let config;
            let name;
            let cat = 'Asymmetric';

            if (isSymmetric) {
                config = generateGrid(cnt, false);
                name = `Grid ${cnt}-${i + 1}`;
                cat = 'Symmetric';
            } else {
                config = generateBSP(cnt, false);
                name = `Collage ${cnt}-${i + 1}`;

                // Sometimes label as Negative Space
                if (Math.random() > 0.8) {
                    // Shrink random asset
                    if (config.length > 0) {
                        config[0].width *= 0.7;
                        config[0].height *= 0.7;
                        config[0].left += 5;
                        config[0].top += 5;
                    }
                    cat = 'Negative Space';
                    name = `Artistic ${cnt}-${i + 1}`;
                }
            }

            values.push(`('${name}', '${cat}', ${cnt}, 1.5, false, '${JSON.stringify(config)}', true)`);
        }
    });

    // --- Spread Layouts ---
    // Generate 20 spread layouts (Counts 4-10)
    for (let i = 0; i < 20; i++) {
        const cnt = 4 + Math.floor(Math.random() * 5); // 4 to 8
        const config = generateBSP(cnt, true); // Width 200
        const name = `Spread Story ${cnt}-${i + 1}`;
        values.push(`('${name}', 'Asymmetric', ${cnt}, 3.0, true, '${JSON.stringify(config)}', true)`);
    }

    sql += values.join(',\n') + ';';

    fs.writeFileSync('seed_layouts.sql', sql);
    console.log('✅ Generated seed_layouts.sql');
}

generateLayouts();
